# Generated by config...
cpp=cc -E
cc=cc
intr_ld=ld
ld=cc
shell=/bin/sh
cppargs=-Wall
ccargs=-g -Wall -c
intr_ldargs=-r
ldargs=
includearg=-I
definearg=-D
libarg=-l
outputarg=-o
preargs=
includes=common/include gui/include os/unix/include read/include write/include
defines=NULL=0
libs=m sweer
incb=`for include in $(includes); do echo " $(includearg) $$include ";done`
defb=`for define in $(defines); do echo " $(definearg) $$define "; done`
libb=`for lib in $(libs); do echo " $(libarg) $$lib "; done`
cext=.c
cppext=.i
objext=.o
mainobj=main.o
bin=bin/posric
installdir=/usr/bin
sourcedirs=common gui os/unix read write
tccbuildf=posric.pjr
cfiles=`for dir in $(sourcedirs); do echo " $$dir/*$(cext) "; done`
cppfiles=`for dir in $(sourcedirs); do echo " $$dir/*$(cppext) "; done`
objfiles=`for dir in $(sourcedirs); do echo " $$dir/*$(objext) "; done`

all: clean makebdir preargs
	for file in $(cfiles); do \
		echo $$file >> $(tccbuildf); \
		echo $(cpp) $(cppargs) $(incb) $(defb) \
			"$$file" $(outputarg) "$$file$(cppext)" | tee /dev/stderr | sh; \
		if test $$? -ne "0"; then\
			exit 1;\
		fi;\
	done

	for file in $(cppfiles); do \
		echo $(cc) $(ccargs) "$$file" $(outputarg) "$$file$(objext)" \
			| tee /dev/stderr | sh; \
		if test "$$?" -ne "0"; then\
			exit 1;\
		fi;\
	done

	for file in $(objfiles); do \
		if test -f "$(mainobj)"; then \
			echo $(intr_ld) $(intr_ldargs) "$$file" "$(mainobj)" $(outputarg) \
				"$(mainobj).tmp.o" | tee /dev/stderr | sh; \
		else \
			cp "$$file" "$(mainobj).tmp.o"; \
		fi; \
		if test "$$?" -ne "0"; then \
			exit 1; \
		fi; \
		mv "$(mainobj).tmp.o" "$(mainobj)"; \
	done

	$(ld) $(libb) $(ldargs) $(mainobj) $(outputarg) $(bin)

clean:
	if [ -f $(tccbuildf) ]; then rm $(tccbuildf); fi
	if [ -f "$(mainobj)" ]; then rm $(mainobj); fi
	if [ -f "$(bin)" ]; then rm $(bin); fi
	for file in  $(cppfiles) $(objfiles); do\
                 if [ -f $$file ]; then rm "$$file"; fi; done

makebdir:
	if [ ! -d bin ]; then mkdir bin; fi

preargs:
	$(shell) pacomp.sh $(preargs) | \
	awk '{if(index($$0, "/*") > 0) print $$0,"\r"; else print $$0,"\\\r"}' \
	> ./common/include/p_prearg.h

install: all
	cp $(bin) $(installdir)
