#!/bin/sh

echo "/* Generated by the Pre-Argument Compilation script */"
echo "#define P_PREARGS()"

for arg in $@; do

    if [ "$arg" = "-n" ]; then
        echo "noScript = true;";
    elif [ "$arg" = "-y" ]; then
        echo "overwrite = true;";
    elif [ "$arg" = "-t" ]; then
        export tmp=true;
    elif [ "$tmp" = true ]; then
        export tmp="";
        echo "argTmp = true;";
        echo "tmpName = \"$arg\"";
    else
        echo "pacomp: Unsupported Argument \"$arg\"!" > /dev/stderr;
        exit 1;
    fi
done
