/* p_skpDta - seeks through the file until a descriptor ridge is found

ARGUMENTS:

FILE *in - the file being seeked through
bool seekBack - if set, p_skpDta seeks back 3 bytes

VARIABLES:

rType ridge - used to get the value of the ridge
byte *ret - used to free the unused buffer generated by p_getRdg

*/

#include <p_skpDta.h>

retVal p_skpDta(FILE *in, bool seekBack)
{
    rType ridge;
    byte *ret;

    p_dontRecDir = true;

    P_FTADD(FUNCNAME);

    while((ret = p_getRdg(in, &ridge)) &&
        ridge + P_RTYPECORR <= P_DATA &&
        !feof(in))

        free(ret);

    if(!ret)
    {
        P_FREEALL();
        return err_unknown;
    }

    if(seekBack) fseek(in, -P_RMINRD, SEEK_CUR);

    P_FREEALL();

    return none;
}
